### ISSUE TITLE
Add solution for Rod Cutting Problem

### ISSUE THREAD

**Issue by wataridori** [wataridori/dynamic-programming#8]

**Comment by dolamanee6122** [comment]
hey @wataridori , I will add a solution for the rod cutting problem in c++. Also in  Java and python if possible.
please assign this issue to me.

**Comment by wataridori** [comment]
@dolamanee6122 Thank you very much. 👍 
I have assigned the issue to you. 

Please take a look at the [contribution guideline](../#contributions) first.
